[package]
name = "gltf-viewer"
version = "0.0.1-pre"
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
description = "Simple glTF 2.0 viewer (WIP)"
repository = "https://github.com/bwasty/gltf-viewer"
readme = "README.md"
keywords = ["glTF", "3D", "model", "scene", "viewer"]
categories = ["rendering"]
license = "Unlicense"

include = [
    "**/*.rs",
    "Cargo.toml",
]

[badges]
travis-ci = { repository = "https://github.com/bwasty/gltf-viewer", branch = "master" }

[dependencies]
cgmath = "0.14.1"
clap = "2.25.0"
futures = "0.1"
gl = "0.6.2"
glfw = "0.15.0"
image = "0.14.0"

[dependencies.gltf]
# branch = "incoming"
# git = "https://github.com/alteous/gltf.git"
path = "../gltf"
